// ============================================================
// DATA SISWA (dari screenshot)
// ============================================================
const siswaData = [
    { nama: "ADE MUSTOPA", nisn: "3139453861", jenjang: "SD" },
    { nama: "AGUS RAMDANI", nisn: "0104915906", jenjang: "SMP" },
    { nama: "AHMAD PADILAH", nisn: "3137836817", jenjang: "SD" },
    { nama: "AI SITI NUROHMAH", nisn: "3158260386", jenjang: "SD" },
    { nama: "ANDIKA NUROHMAN", nisn: "0141419382", jenjang: "SD" },
    { nama: "ANISA SAPUTRI", nisn: "0123595071", jenjang: "SMP" },
    { nama: "ARDIANSYAH SAPUTRA", nisn: "3162522983", jenjang: "SD" },
    { nama: "ARIF FIRMANSYAH", nisn: "3120690349", jenjang: "SD" },
    { nama: "ARMAN MAULANA", nisn: "3132152714", jenjang: "SMP" },
    { nama: "DEPAHRI PUTRA RAMADAN", nisn: "3111636292", jenjang: "SMP" },
    { nama: "DERIMUHAMMAD", nisn: "3122527422", jenjang: "SMP" },
    { nama: "DEWANGGNA NUGRAHA", nisn: "3124835417", jenjang: "SMP" },
    { nama: "DEWI TANIA", nisn: "3124764226", jenjang: "SD" },
    { nama: "ELSA SABILA NURHALIMAH", nisn: "3130228888", jenjang: "SMP" },
    { nama: "EVA FAUZIAH", nisn: "0094884752", jenjang: "SMP" },
    { nama: "FANESA ANASTASYA", nisn: "0106857181", jenjang: "SMP" },
    { nama: "FEBI", nisn: "0129226857", jenjang: "SD" },
    { nama: "HISMA HOLIPATUL PADILAH", nisn: "0113316745", jenjang: "SMP" },
    { nama: "IHSAN MAULANA", nisn: "3126090468", jenjang: "SMP" },
    { nama: "INDRIA DELIA PUTRI", nisn: "97311050", jenjang: "SMP" },
    { nama: "IRNA RAODOTUL ZANAH", nisn: "3133143373", jenjang: "SMP" },
    { nama: "IRSAL KHAERUNA", nisn: "3146716444", jenjang: "SD" },
    { nama: "LESTI JULIANTI", nisn: "3128365677", jenjang: "SMP" },
    { nama: "M RIZKY MAULANA", nisn: "3172776475", jenjang: "SD" },
    { nama: "M. FATIR", nisn: "0102903616", jenjang: "SMP" },
    { nama: "MOCH AKBAR TRI HERMAWAN", nisn: "0106566909", jenjang: "SMP" },
    { nama: "MOH PAISAL APRILIANSAH", nisn: "0147560005", jenjang: "SD" },
    { nama: "MUHAMAD FATTAN SAPUTRA", nisn: "3155276593", jenjang: "SD" },
    { nama: "MUHAMAD HANIF ALIYUDIN", nisn: "102243542", jenjang: "SMP" },
    { nama: "MUHAMAD HASANUDIN", nisn: "0113191027", jenjang: "SMP" },
    { nama: "MUHAMAD REHAN NURUL JANAH", nisn: "0111987988", jenjang: "SMP" },
    { nama: "MUHAMAD RISKI ABDULLOH", nisn: "3161059263", jenjang: "SD" },
    { nama: "MUHAMAD RIVAL ALFARIZI", nisn: "3169279715", jenjang: "SD" },
    { nama: "MUHAMAD SAMIN NUGRAHA", nisn: "0119673298", jenjang: "SMP" },
    { nama: "MUHAMAD SANDI", nisn: "0115109325", jenjang: "SMP" },
    { nama: "MUHAMMAD IDRUS PAHMI JAHARSAH", nisn: "0115015547", jenjang: "SMP" },
    { nama: "MUHAMMAD RAEHAN", nisn: "3094108589", jenjang: "SMP" },
    { nama: "MUHAMMAD ZAKI ARIPIN", nisn: "0127300770", jenjang: "SMP" },
    { nama: "MUSNAN FIRDAUS", nisn: "3108593390", jenjang: "SMP" },
    { nama: "NAZHAN", nisn: "0102332909", jenjang: "SD" },
    { nama: "NOVI RAHMADANI", nisn: "0127825608", jenjang: "SMP" },
    { nama: "PARHAN HERIYANSAH", nisn: "3137252816", jenjang: "SMP" },
    { nama: "PERDIANSAH PRATAMA", nisn: "0128988677", jenjang: "SMP" },
    { nama: "PIRMANSYAH RAMDANI", nisn: "3108187441", jenjang: "SMP" },
    { nama: "PONI YULIA", nisn: "0124893928", jenjang: "SD" },
    { nama: "RAIHAN SAPUTRA", nisn: "0119552685", jenjang: "SMP" },
    { nama: "RAISA AURELIA PUTRI", nisn: "3142169447", jenjang: "SD" },
    { nama: "RAISYA NURPADILAH", nisn: "0104449370", jenjang: "SMP" },
    { nama: "RANI", nisn: "3128636723", jenjang: "SMP" },
    { nama: "RAYAA RAFSANJANI", nisn: "3151327926", jenjang: "SD" },
    { nama: "REGI", nisn: "0092815396", jenjang: "SMP" },
    { nama: "REHAN", nisn: "0098060608", jenjang: "SMP" },
    { nama: "REZA HANAFIYAH", nisn: "3129196277", jenjang: "SMP" },
    { nama: "RINA", nisn: "3129604730", jenjang: "SMP" },
    { nama: "RISKY", nisn: "0103304248", jenjang: "SMP" },
    { nama: "RIYAD FADILAH", nisn: "0131133087", jenjang: "SD" },
    { nama: "RIYAN AGUNG FAUZI", nisn: "3129425558", jenjang: "SD" },
    { nama: "RIZKI MIRAJ NAWAWI", nisn: "3120958649", jenjang: "SD" },
    { nama: "SABIT MAULANA", nisn: "3117684281", jenjang: "SMP" },
    { nama: "SALMAN SAEPUL BAGRI", nisn: "0115635878", jenjang: "SMP" },
    { nama: "SALSA BILA", nisn: "0124232598", jenjang: "SMP" },
    { nama: "SALWA AULIA ZAKIAWAN", nisn: "0109385868", jenjang: "SMP" },
    { nama: "SELLI KHAIRUNNISA", nisn: "3124008773", jenjang: "SMP" },
    { nama: "SIFA NURAINI", nisn: "0103955647", jenjang: "SMP" },
    { nama: "SITI FADILAH", nisn: "3154325333", jenjang: "SD" },
    { nama: "SITIMASITOH", nisn: "3125474904", jenjang: "SMP" },
    { nama: "SITIPASWA", nisn: "3131493765", jenjang: "SMP" },
    { nama: "SRIMULYANI", nisn: "0108334564", jenjang: "SMP" },
    { nama: "SUDIRMAN", nisn: "0119440168", jenjang: "SMP" },
    { nama: "SYIFANURHAYATI", nisn: "0103927661", jenjang: "SMP" },
    { nama: "YAN YAN ABDUL HADI", nisn: "0106183939", jenjang: "SMP" },
    { nama: "YANA MULYANA", nisn: "3138754482", jenjang: "SD" },
    { nama: "YUSUP AWALUDIN", nisn: "0114870689", jenjang: "SMP" },
    { nama: "ZAKI MUHAMAD KUSUMAH", nisn: "3133946425", jenjang: "SD" },
    { nama: "ZIDAN ABDUL JAILANI", nisn: "3169526039", jenjang: "SD" }
];

// ============================================================
// DATA MATERI AJAR DEFAULT (LENGKAP SD, SMP, SMA)
// ============================================================
const defaultMateriPancasila = [
    // SD Kelas 1-6
    { id: 1, kelas: 1, jenjang: "SD", judul: "Aku Cinta Pancasila", deskripsi: "Pengenalan lambang dan bunyi Pancasila", konten: "<p>Pancasila adalah dasar negara Indonesia. Terdiri dari lima sila...</p><ul><li>Sila ke-1: Ketuhanan Yang Maha Esa</li><li>Sila ke-2: Kemanusiaan yang Adil dan Beradab</li><li>Sila ke-3: Persatuan Indonesia</li><li>Sila ke-4: Kerakyatan yang Dipimpin oleh Hikmat Kebijaksanaan dalam Permusyawaratan/Perwakilan</li><li>Sila ke-5: Keadilan Sosial bagi Seluruh Rakyat Indonesia</li></ul>", sumber: "Buku PPKn SD Kelas I" },
    { id: 2, kelas: 2, jenjang: "SD", judul: "Hidup Rukun dengan Pancasila", deskripsi: "Menerapkan nilai-nilai Pancasila dalam kehidupan sehari-hari", konten: "<p>Nilai-nilai Pancasila dapat kita terapkan di rumah, sekolah, dan masyarakat...</p>", sumber: "Buku PPKn SD Kelas II" },
    { id: 3, kelas: 3, jenjang: "SD", judul: "Sikap Sesuai Pancasila", deskripsi: "Mengidentifikasi sikap yang sesuai dan tidak sesuai dengan Pancasila", konten: "<p>Sikap baik seperti tolong-menolong, menghargai perbedaan, dan gotong royong adalah contoh pengamalan Pancasila...</p>", sumber: "Buku PPKn SD Kelas III" },
    { id: 4, kelas: 4, jenjang: "SD", judul: "Makna Sila-Sila Pancasila", deskripsi: "Mendalami makna setiap sila", konten: "<p>Setiap sila memiliki makna yang dalam, misalnya sila ke-1 mengajarkan kita untuk beriman dan bertakwa...</p>", sumber: "Buku PPKn SD Kelas IV" },
    { id: 5, kelas: 5, jenjang: "SD", judul: "Penerapan Pancasila dalam Berbangsa", deskripsi: "Penerapan Pancasila di lingkungan bangsa", konten: "<p>Pancasila menjadi panduan dalam kehidupan berbangsa dan bernegara...</p>", sumber: "Buku PPKn SD Kelas V" },
    { id: 6, kelas: 6, jenjang: "SD", judul: "Pancasila dan Konstitusi", deskripsi: "Hubungan Pancasila dengan UUD 1945", konten: "<p>Pancasila adalah sumber dari segala sumber hukum di Indonesia...</p>", sumber: "Buku PPKn SD Kelas VI" },
    // SMP Kelas 7-9
    { id: 7, kelas: 7, jenjang: "SMP", judul: "Pancasila sebagai Pandangan Hidup", deskripsi: "Memahami Pancasila sebagai ideologi dan pandangan hidup bangsa", konten: "<p>Pancasila bukan hanya dasar negara, tetapi juga pandangan hidup yang mempersatukan...</p>", sumber: "Buku PPKn SMP Kelas VII" },
    { id: 8, kelas: 8, jenjang: "SMP", judul: "Nilai-Nilai Pancasila", deskripsi: "Mengidentifikasi nilai-nilai Pancasila dalam kehidupan", konten: "<p>Nilai ketuhanan, kemanusiaan, persatuan, kerakyatan, dan keadilan...</p>", sumber: "Buku PPKn SMP Kelas VIII" },
    { id: 9, kelas: 9, jenjang: "SMP", judul: "Pancasila dalam Sejarah", deskripsi: "Perjalanan Pancasila dari masa ke masa", konten: "<p>Pancasila dirumuskan oleh para pendiri bangsa pada tahun 1945...</p>", sumber: "Buku PPKn SMP Kelas IX" },
    // SMA Kelas 10-12
    { id: 10, kelas: 10, jenjang: "SMA", judul: "Filsafat Pancasila", deskripsi: "Pendalaman filosofis tentang Pancasila", konten: "<p>Pancasila sebagai sistem filsafat yang holistik...</p>", sumber: "Buku PPKn SMA Kelas X" },
    { id: 11, kelas: 11, jenjang: "SMA", judul: "Pancasila dan Demokrasi", deskripsi: "Hubungan Pancasila dengan sistem demokrasi", konten: "<p>Demokrasi Pancasila berbeda dengan demokrasi liberal...</p>", sumber: "Buku PPKn SMA Kelas XI" },
    { id: 12, kelas: 12, jenjang: "SMA", judul: "Pancasila di Era Globalisasi", deskripsi: "Tantangan dan peluang Pancasila di era global", konten: "<p>Globalisasi membawa perubahan, namun Pancasila tetap menjadi filter budaya asing...</p>", sumber: "Buku PPKn SMA Kelas XII" }
];
